version: 2
jobs:
  build:
    name: Build
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  deploy_web:
    name: Deploying Web
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: sudo npm install -g create-react-app
      - run: sudo npm install -g syncano-cli@beta
      - run:
          name: yarn
          command: yarn
          working_directory: ~/repo/web/
      - run:
          name: Build
          command: yarn build
          working_directory: ~/repo/web/
      - run: s deploy
      - run: s hosting sync app


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy_web:
          requires:
            - build
